# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: alesker
title_separator: "|"
subtitle: Coding with spices 🌶
name: &name Ilya Alesker
email: ilya.alesker@gmail.com
description: >-
    My name is Ilya Alesker and I am software developer from Riga currently working at Pipedrive and based in Tallinn.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
paginate: 5
permalink: /:categories/:title/
search: true
theme: minimal-mistakes-jekyll

social:
  type: Person
  links:
    - &twitter_url "https://twitter.com/evil_cormorant"
    - &facebook_url "https://facebook.com/ilya.alesker"
    - &github_url "https://github.com/alesker"
    - &instagram_url "https://instagram.com/evil_cormorant"
    - &linkedin_url "https://www.linkedin.com/in/ilyaalesker"

author:
  name: *name
  avatar: "/assets/images/avatar.jpg"
  bio: "iOS dev at Pipedrive, New Jersey Devils fan"
  location: "Tallinn, Estonia / Riga, Latvia"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: *github_url
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: *twitter_url
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: *linkedin_url
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: *instagram_url

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: *twitter_url
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: *github_url

plugins:
  - jekyll-feed

include:
  - _pages
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      author_profile: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

